extends: spectral:oas
rules:
  operation-tag-defined: error
  operation-description: error  
  oas3-valid-oas-content-example: error
  patch-post-must-have-examples:
    description: Patch and Post endpoints must have examples
    given: $.paths[*][?( @property === 'patch' || @property === 'post')]
    severity: error
    then:
      field: requestBody.content.application/json.examples
      function: truthy